### PR TITLE
Add minimum character constraints to random_string

### PR DESCRIPTION
**Pull request by phekmat**
The motivation behind this is to more reliably create passwords that will pass complexity requirements

### CODE REVIEW

**Comment by mildwonkey** [comment]
Thanks for adding this feature :)

**Comment by mildwonkey** [comment]
@kitsunde I'm sorry to hear about that and thanks for sharing the workaround. I'm certain it wasn't the intent of this PR - I will take a look at it.

**Comment by phekmat** [comment]
Apologies all. @mildwonkey I'm still relatively new with terraform providers, but I think the correct approach is to use a state migration to add the defaults to the instance state. I've opened a PR with that change (#29)

**Comment by mildwonkey** [comment]
Thank you @phekmat - I opened #28 just a few minutes before you with basically the same function. (I'm also new to this!) I'll close my PR; it was a good learning experience for me but we should let you own the fix.

**Comment by ChrisAnn** [comment]
This hit us too and we had a short production outage as a result :sob:

**Pull request merged**
