### PR TITLE
Scrub ID for random_string resource

### LINKED ISSUE #17: "random_string" prints sensitive data to console
"random_string"uses the generated random string as id. The id will be printed to the console like "random_string.password: Refreshing state... (ID: s**********)" when executing `terraform plan`.  If you want to use an random_string as an password, you won't like your sensitive data printed to the console.

### Terraform Version
Terraform v0.11.2
+ provider.azurerm v1.0.1
+ provider.random v1.1.0

### Affected Resource(s)
- provider.random

### Expected Behavior
random string should not use the result as id, because it could be sensitive data and will be output when running terraform plan: "random_string.password: Refreshing state... (ID: s**********)"

### Actual Behavior
random string uses the result as id and outputs it when running "terraform plan"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a "random_string"
2. `terraform plan`

### PR DESCRIPTION
**Pull request by Ginja**
Fixes #17

Sets the ID for `random_string` resources to `"none"`.

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

  + random_string.password
      length:  "16"
      lower:   "true"
      number:  "true"
      result:  "<computed>"
      special: "true"
      upper:   "true"


Plan: 1 to add, 0 to change, 0 to destroy.


$ terraform apply
random_string.password: Creating...
  length:  "" => "16"
  lower:   "" => "true"
  number:  "" => "true"
  result:  "" => "<computed>"
  special: "" => "true"
  upper:   "" => "true"
random_string.password: Creation complete (ID: none)

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

random_string.password: Refreshing state... (ID: none)
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, Terraform
doesn't need to do anything.


$ terraform apply
random_string.password: Refreshing state... (ID: none)

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### CODE REVIEW

**Comment by Ginja** [comment]
@apparentlymart thoughts?

**Comment by apparentlymart** [comment]
Hi @Ginja! Thanks for working on this, and sorry for the late response.

Looking at this resource again, I realize that it doesn't actually use the saved id value at all, and so it really doesn't matter what is stored in here. I assume your goal here was to just avoid showing the generated random string in the log output, in which case maybe it'd be simpler to just set the id to a hard-coded value (like `d.SetId("none")`) and then we'd avoid the complexity of including bcrypt and make the output simpler:

```
random_string.password: Refreshing state... (ID: none)
```

What do you think?

I know it's been a while since you submitted this so if you no longer have time to work on this please let me know and I can work on a simplified version myself when I get some spare moments.

**Comment by Ginja** [comment]
Done :) 

I also went ahead and just squashed the two commits to avoid confusion.

**Comment by apparentlymart** [comment]
Hi @Ginja! Thanks for the updated version.

Although we do document that `result` is the way to get the random result from this resource, it is possible that someone would currently be using `random_string.foo.id` which would then be broken by this.

Because of that, we'll need to make a major release in order to incorporate this. This is not a big problem, but we have some other changes that will warrant a major version bump coming up as part of our configuration language improvement project, so if it's okay with you I'd like to hold this for a little while so we can release these things together. The timeline here would be at some point in the next few months, depending on where some other work lands in Terraform Core.

Thanks again for working on this!

**Comment by Ginja** [comment]
No problem! Sounds good to me.

**Comment by blackjid** [comment]
can wait

**Comment by danmerron-sig** [comment]
This is a problem for us too. Do we have any ETA for this being merged?

**Comment by tinder-jlee** [comment]
I think setting the ID to "none" is not really a good approach. It seems it may hurt the "consistency" with the way how resources are managed. For example, `archive_file` resource generates a unique ID, and this ID is what addresses that particular resource.
So, I'd rather leave the `id` to address the resource itself while setting `result` to be the actual random string generated.

**Comment by dpmerron-ltd** [comment]
See my PR above to address the issue of not setting the random_string id to ‘none’.

The way I see it working the random_password resource should never really require an ID so really does address the issue.

**Comment by Ginja** [comment]
@mildwonkey Done 😃

**Pull request merged**
