### PR TITLE
Random string generator

### PR DESCRIPTION
**Pull request by ryan-dyer-sp**
Random string generator which can be used in places where other random_ resources do not suffice.  ie for passwords where due to compliance reasons, alphanumeric and special characters are required.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @ryan-dyer-sp! Thanks for working on this.

This looks good to me from an implementation standpoint.

I have a question about the use-case, though: if generating random passwords is the goal, shouldn't it be able to guarantee at least one of each requested class of character in order to comply with password requirements? Otherwise this resource would not necessarily generate policy-compatible passwords, I think.

Looking at this I also notice that the tests in this provider are all using `resource.Test` rather than `resource.UnitTest`, which means they will only work when in acceptance test mode. I'd like to fix that in a separate PR since these tests don't interact with anything outside of Terraform anyway; perhaps you'd like to update just your new test here to use `UnitTest` and then I can take care of the rest separately. (No worries if not... I can just wait until this is merged and do it.)

Thanks again!

**Comment by ryan-dyer-sp** [comment]
In regards to the use case, you're right.  I'm just looking to get something that's close and generic.  Given a high enough length, its extremely unlikely you would encounter a string which wouldn't contain at least one lower, upper, num, and special.  The use case of passwords and exact compliance would be a significantly more difficult undertaking imo.

And in regards to the test, I just mimiced what the random_id was doing for tests.  I cant say I'm familiar with the proper way of doing this.

**Comment by apparentlymart** [comment]
Thanks again for this, @ryan-dyer-sp!

Before merging I made a couple tweaks:
* I renamed the computed attribute to `result` for consistency with some of the other resources.
* The linter complained about the variable names with underscores so I just renamed them to use camelcase to conform with usual Go style.

I also added the commit I made to make the tests run as unit tests, which means that they get included in the travis runs we do here for PRs. That's not directly related to your change, but it made it easier for me to verify it before merging.

**Comment by ryan-dyer-sp** [comment]
@apparentlymart  Awesome.  When/How is this made available?  I've built it locally and using that for now, but others on team use macs (ubuntu here) and so we're dealing with how to distribute multiple compiled versions.

**Pull request merged**
